### ISSUE TITLE
Problem: We haven't tested the CCIP bridge

### ISSUE THREAD

**Issue by itscameronlee** [truflation/truflation-contracts#37]
@Dev-Doggo since you will be handling this can you take ownership of this issue?

 _Originally posted by @itscameronlee in [#40](https://github.com/truflation/truf-claim-page/issues/40#issuecomment-2071150561)_

**Comment by markholdex** [comment]
All contract addresses that are currently used by the bridge app are here: https://github.com/truflation/truf-claim-page/blob/main/src/config/networks.ts

We are using the Sender contract on testnet because we haven't been successful otherwise. @lewis999bits has deployed the Sender contract here: https://github.com/truflation/truf-ccip-bridge/pull/2

@Dev-Doggo when we deploy bridge to production, we will need to deploy the Sender contract on all main networks. Otherwise, the UI will not function.

**Comment by Dev-Doggo** [comment]
@zolotokrylin I don't think we have receiver contracts? They shouldn't be necessary for the bridge to function. 
Sender contracts should be deployed though, yes. (@markholdex)

**Comment by zolotokrylin** [comment]
@Dev-Doggo are you only advising, or you are code contributor as well? 

If you are not working on anything else, please add missing Problem statements in the Goal issue and help to execute them (follow Developer Guidelines).

Thank you.

**Comment by Dev-Doggo** [comment]
> @Dev-Doggo are you only advising, or you are a code contributor as well?
> 
> If you are not working on anything else, please add missing Problem statements in the Goal issue and help to execute them (follow Developer Guidelines).
> 
> Thank you.

@zolotokrylin I can contribute solidity/backend code but I don't see any issues that relate to those that noone else has picked up already, if we agree to add a fee to the contracts I'll work on that & the testing. (https://github.com/truflation/truf-claim-page/issues/40#issuecomment-2074557130)

**Comment by itscameronlee** [comment]
Hey @Dev-Doggo I'll answer the point about the fees in [the issue about bridge revenue](https://github.com/truflation/truf-claim-page/issues/146), but I want to clarify something here.

I was under the impression that once the CCIP pools are enabled by Chainlink, we wouldn't need any custom Solidity code between our frontend and the CCIP pool.

But I see now we're talking about using [CCIPBridgeProxy.sol](https://github.com/truflation/truf-ccip-bridge/blob/main/src/CCIPBridgeProxy/CCIPBridgeProxy.sol). I have a few questions about this:

1. Where did this code come from?
2. Has it been audited?
3. Is it necessary to use this proxy contract, or can we interface directly with the CCIP pool?
4. When you say adding a fee is easy, does that functionality depend on using this proxy?

Thanks, I just want to make sure I understand what we're doing.

**Comment by Dev-Doggo** [comment]
Hey @itscameronlee

> 1. Where did this code come from?

It's a slightly modified version of the code we used for NUON (was required back then due to the whitelist, I worked on this).

> 2. Has it been audited?

No we didn't audit this part, the code is really simple though.

> 3. Is it necessary to use this proxy contract, or can we interface directly with the CCIP pool?

We can interface directly with the pool, but I think the frontend guys had issues interfacing directly with it, I could help to get those resolved if we decide against going with the proxy.

> 4. When you say adding a fee is easy, does that functionality depend on using this proxy?

Yes it does

**Comment by itscameronlee** [comment]
Thank you @Dev-Doggo 

As a general rule, now that our token is live and has real value, I would prefer we don't release unaudited code. Whether or not this specific piece of code needs to be audited I will leave to you, @zolotokrylin, and @markholdex to figure out.

**Comment by Dev-Doggo** [comment]
> Thank you @Dev-Doggo
> 
> As a general rule, now that our token is live and has real value, I would prefer we don't release unaudited code. Whether or not this specific piece of code needs to be audited I will leave to you, @zolotokrylin, and @markholdex to figure out.
> 
> Ideally we have the conversation here on GitHub so I can see the thought process.

@itscameronlee I understand, and if you guys want to go ahead and release the bridge with no proxy for now (as we're in a bit of a rush to do so) and then work/audit a proxy later which will add our fee on top of it I'm totally okay with that.
As a note though an audit in this case is really unnecessary IMO, totally get it if you guys want to do one just to feel safer though!

**Comment by markholdex** [comment]
> Thank you @Dev-Doggo
> 
> As a general rule, now that our token is live and has real value, I would prefer we don't release unaudited code. Whether or not this specific piece of code needs to be audited I will leave to you, @zolotokrylin, and @markholdex to figure out.
> 
> Ideally we have the conversation here on GitHub so I can see the thought process.

@itscameronlee I believe that the Sender contract [CCIPBridgeProxy](https://github.com/truflation/truf-ccip-bridge/blob/main/src/CCIPBridgeProxy/CCIPBridgeProxy.sol) doesn't have to be audited. The reason for that is because the functions are developed according to the official [Chainlink Documentation](https://docs.chain.link/ccip/tutorials/cross-chain-tokens) and they don't perform any unintended actions. Attempting to exploit the contract, would not favor the `bad actor` because the requests are redirected to the official Chainlink CCIP contract which is responsible for handling the bridge logic.

Additionally, by using the [CCIPBridgeProxy](https://github.com/truflation/truf-ccip-bridge/blob/main/src/CCIPBridgeProxy/CCIPBridgeProxy.sol) we are not manipulating our users to transfer their tokens to an unknown address. The contract logic has been tested to execute its intended actions. The users can actually benefit from it because any additional amount of `ETH` sent for the fees will be returned to their wallet. 

CC @zolotokrylin @Dev-Doggo

**Comment by Dev-Doggo** [comment]
Bridge has been tested on sepolia, sepolia base & sepolia arbitrum
